### ISSUE TITLE
cancel one order doesn't work

### ISSUE THREAD

**Issue by morcano** [y0un1verse/bitmex-api-php#6]
When I try cancel 1 order I got error:
orderIDs or clOrdIDs must be sent

**Comment by morcano** [comment]
Thanks!

**Comment by BitVlie** [comment]
I do this :+1: 
public function cancelOpenOrder($orderID) {
   $symbol = self::SYMBOL;
   $data['method'] = "DELETE";
   $data['function'] = "order";
   $data['params'] = array(
      "orderID" => $orderID
    );
    return $this ->authQuery($data);
}
and this :+1: 

Here is the fix
In the function
private function authQuery($data) {
after
elseif($method == "DELETE") {
replace :
$params = json_encode($data['params']);
with:
$params = http_build_query( $data['params'] );

in index.php i do this :+1: 
$orderID =  "9672735a-7a11-f829-99f1-bee99c5a9ad6";
   $cancelOpenOrders = $bitmex->cancelOpenOrders($orderID) ;
var_dump ($cancelOpenOrders);

and i get this in browser :+1: 
bool(false)

What do i wrong ?
