### ISSUE TITLE
How to cancel the order by using "Filter" through Bitmex API

### ISSUE THREAD

**Issue by ragupathis** [y0un1verse/bitmex-api-php#8]
Hello., 

We are trying to cancel the all of the Long or short orders but when I execute the Cancel all order function it canceled the Both Long and Short order, so I used a filter to cancel any one of long or short order but that code is not working. 

In Bitmex API explorer we can able to run the canceling Short/Long orders but when i do the same with PHP code it's not working. 

 
public function cancelAllOpenOrders($filter,$text = "") {

    $symbol = self::SYMBOL;
    $data['method'] = "DELETE";
    $data['function'] = "order/all";
    $data['params'] = array(
      "symbol" => $symbol,
      "filter" => $filter,
      "text" => $text
    );

    return $this->authQuery($data);
  }

this is the code I used to cancel the order but it canceled all of the short and long orders but I want to cancel anyone of it.

**Comment by coinnodenl** [comment]
$filter has to be '{"side":"Buy/Sell"}', what is your output?

**Comment by ragupathis** [comment]
We have solved this issue.
The approach is, we used "Content-type:application/json" in curl request.
